### ISSUE TITLE
Expand Gazetteer lists based on Feedback from IST Research

### ISSUE THREAD

**Issue by lewismc** [lewismc/legisgate#2]
The idea here is to obtain feedback from Curtis Goodman @IST Research based on the domain vocabularies they have for characterizing specific domains. Such vocabularies can easily be translated into Gazetteer lists.

**Comment by lewismc** [comment]
lmcgibbn@LMC-032857 /usr/local/legisgate/gate_gazetteers(master) $ git push origin master
Username for 'https://github.com': lewismc
Password for 'https://lewismc@github.com':
Counting objects: 5, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 2.61 KiB | 0 bytes/s, done.
Total 5 (delta 2), reused 0 (delta 0)
To https://github.com/lewismc/legisgate.git
   ea9aba2..08e9841  master -> master

**Comment by chrismattmann** [comment]
Acked
